# Generated by Django 4.2.7 on 2026-02-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=50, unique=True)),
                ("Password", models.CharField(max_length=50)),
                ("RegDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ExpenseItem", models.CharField(max_length=50, null=True)),
                ("ExpenseDtae", models.DateField(blank=True, null=True)),
                ("ExpenseCose", models.FloatField()),
                ("NoteDate", models.DateField(auto_now_add=True)),
                (
                    "UserId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expense.userdetail",
                    ),
                ),
            ],
        ),
    ]
