# Generated by Django 4.2.7 on 2026-02-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="ExpenseCose",
            new_name="ExpenseCost",
        ),
    ]
